name: Test project
on: push
jobs: 
  runs-on: ubuntu-latest
  step:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Install nodeJs
      uses: actions/setup-node@v3
      with: 
        node-version: 18
    - name: Install Dependencies 
      run: npn ci
    - name: Test Run
      run: npn test
